### ISSUE TITLE
Blocks sometimes merge into others when moving left or right at the same time they are moving down

### ISSUE THREAD

**Issue by rethanon** [wynand1004/Projects#1]
I think to solve this the functions move_left and move_right just need to have an extra check i.e.
for move_left - if grid[self.y][self.x - 1] == 0 **and grid[self.y + 1][self.x - 1] == 0**:
for move_right - if grid[self.y][self.x + 1] == 0 **and grid[self.y + 1][self.x + 1] == 0**:

**Comment by wynand1004** [comment]
Thanks! Sorry I didn't see this sooner!
